import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main>
        

        <div className="sidebarright ">
          {/* <a className="active" href="#home">
            Home
          </a> */}
          <a className="active" href="#contact">
            <i className="bi bi-x-lg" />
            <span className="hiddentext">Home</span>
          </a>
          <a href="#contact">
            <i className="bi bi-x-lg" />
            <span className="hiddentext">Contact</span>
          </a>
          <a href="#contact">
            <i className="bi bi-x-lg" />
            <span className="hiddentext">Contact</span>
          </a>
          <a href="#contact">
            <i className="bi bi-x-lg" />
            <span className="hiddentext">Contact</span>
          </a>
        </div>

        <div className="topnav">
          <a className="active" href="#contact">
            {/* <img src="./ig.png" alt="jacket" width="500" height="600" /> */}
          </a>
          <a href="#contact" className="split">
            <i className="bi bi-x-lg" />
            <span className="hiddentext">Contact</span>
          </a>
        </div>

        <div className="content">
          <h2>Responsive Sidebar Example</h2>
          <p>
            This example use media queries to transform the sidebar to a top
            navigation bar when the screen size is 700px or less.
          </p>
          <p>
            We have also added a media query for screens that are 400px or less,
            which will vertically stack and center the navigation links.
          </p>
          <h3>Resize the browser window to see the effect.</h3>
        </div>
      </main>


    </div>
  )
}
