import Head from "next/head";
import Image from "next/image";
import logofull from "../public/ig.png";
import logo from "../public/instagram-logo-2022_freelogovectors.net_.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <style>
        {`
        .main{
          width: 100%;
          padding: 40px 0;
          display: flex;
          justify-content: center;
          margin-top: 50px;
      }
      
      .wrapper{
          width: 100%;
          max-width: 1000px;
          display: grid;
          grid-template-columns: 60% 40%;
          grid-gap: 30px;
      }
      
      .left-col{
          display: flex;
          flex-direction: column;
      }
      
      .status-wrapper{
          width: 100%;
          height: 120px;
          background: #fff;
          border: 1px solid #dfdfdf;
          border-radius: 2px;
          padding: 10px;
          padding-right: 0;
          display: flex;
          align-items: center;
          overflow: hidden;
          overflow-x: auto;
      }
      
      .status-wrapper::-webkit-scrollbar{
          display: none;
      }
      
      .status-card{
          flex: 0 0 auto;
          width: 80px;
          max-width: 80px;
          display: flex;
          flex-direction: column;
          align-items: center;
          margin-right: 15px;
      }
      
      .profile-pic{
          width: 70px;
          height: 70px;
          border-radius: 50%;
          overflow: hidden;
          padding: 3px;
          background: linear-gradient(45deg, rgb(255, 230, 0), rgb(255, 0, 128) 80%);
      }
      
      .profile-pic img{
          width: 100%;
          height: 100%;
          object-fit: cover;
          border-radius: 50%;
          border: 2px solid #fff;
      }
      
      .username{
          width: 100%;
          overflow: hidden;
          text-align: center;
          font-size: 12px;
          margin-top:5px;
          color: rgba(0, 0, 0, 0.5)
        `}
      </style>

      <main>
        <div div class="wrapper">
          <div class="left-col">
            <div class="status-wrapper">
              <div class="status-card">
                <div class="profile-pic">
                  <Image src={logo} alt="" />
                </div>
                <p class="username">user_name_1</p>
              </div>
              <div class="status-card">
                <div class="profile-pic">
                  <Image src={logo} alt="" />
                </div>
                <p class="username">user_name_2</p>
              </div>
              <div class="status-card">
                <div class="profile-pic">
                  <Image src={logo} alt="" />
                </div>
                <p class="username">user_name_3</p>
              </div>
              <div class="status-card">
                <div class="profile-pic">
                  <Image src={logo} alt="" />
                </div>
                <p class="username">user_name_3</p>
              </div>
              <div class="status-card">
                <div class="profile-pic">
                  <Image src={logo} alt="" />
                </div>
                <p class="username">user_name_3</p>
              </div>
              <div class="status-card">
                <div class="profile-pic">
                  <Image src={logo} alt="" />
                </div>
                <p class="username">user_name_3</p>
              </div>
              <div class="status-card">
                <div class="profile-pic">
                  <Image src={logo} alt="" />
                </div>
                <p class="username">user_name_3</p>
              </div>
              <div class="status-card">
                <div class="profile-pic">
                  <Image src={logo} alt="" />
                </div>
                <p class="username">user_name_3</p>
              </div>
              <div class="status-card">
                <div class="profile-pic">
                  <Image src={logo} alt="" />
                </div>
                <p class="username">user_name_3</p>
              </div>

              {/* // +5 more status card elements. */}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
