import Link from "next/link";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import logofull from "../../public/ig.png";
import logo from "../../public/instagram-logo-2022_freelogovectors.net_.png";
import logo1 from "../../public/instagram-logo-2022_freelogovectors.net_1.png";

export default function Layout({ children }) {
  const router = useRouter();

  const menuItems = [
    {
      href: "/",
      title: "home",
    },
    {
      href: "/login",
      title: "login",
    },
    {
      href: "/contact",
      title: "Contact",
    },
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <style>
        {`
        main,html{
          background:#f1f1f1;
        }
        p {
          margin-bottom: 0px;
        }
          .sidebar {
            margin: 0;
            // padding: 0;
            width: 20%;
            background-color: #FFFFFF;
            position: fixed;
            height: 100%;
            overflow: auto;
            // padding-top: 10px;
            border-right-style: solid;
            border-color: #d1dae1;
            border-width: 1px;
            z-index: 1;


          }
          .sidebar a {
            display: block;
            color: black;
            padding: 16px;
            text-decoration: none;
            // padding: 6px 8px 6px 16px;
            font-size: 18px;

          }
          .sidebar a.active {
            background-color: #502b17;
            color: white;
          }
          .sidebar a:hover:not(.active) {
            background-color: #fff5de;
            color: #502b17;
          }

          .topnav {
            margin: 0;
            padding: 0;
            // width: 20%;
            background-color: #FFF;
            position: fixed;
            height: 100%;
            overflow: auto;
            z-index: 1;
          }
          
          .topnav a {
            float: left;
            display: block;
            color: black;
            // padding: 8px;
            text-decoration: none;
          }
          
          // .topnav a:hover {
          //   background-color: #ddd;
          //   color: black;
          // }
          
          .topnav a.split {
            float: right;
            // background-color: #04AA6D;
            color: black;
            padding: 12px;
          }
          div.content {
            margin-left: 28%;
            // margin-right: 30px;

            // padding: 1px 16px;
            // height: 100vh;
            padding-top: 0px;
            max-width : 965px;
            width : 65%;
            // max-width: 300px;
            
            // margin: auto;
          }



          .profile-card{
            width: fit-content;
            display: flex;
            justify-content: center;
            align-items: center;
            margin-bottom: 10px;
        }
        
        .profile-card .profile-pic{
            flex: 0 0 auto;
            padding: 0;
            background: none;
            width: 40px;
            height: 40px;
            margin-right: 10px;
        }
        
        .profile-card:first-child .profile-pic{
            width: 56px;
            height: 56px;
        }
        
        .profile-card .profile-pic .Image{
            border: none;
        }
        
        .profile-card .username{
            font-weight: 500;
            font-size: 14px;
            color: #000;
        }
        
        .sub-text{
            color: rgba(0, 0, 0, 0.5);
            font-size:12px;
            font-weight: 500;
            margin-top: 5px;
        }
      

        .action-btn{
          width: 70px;
          height: 100%;
          background: none;
          border: none;
          outline: none;
          text-transform: capitalize;
          font-size: 14px;
          color: rgb(0, 162, 255);
          font-weight: 700;
          // opacity: 0.5;
          opacity: 1;
      }
        
        .suggestion-text{
            font-size: 14px;
            color: rgba(0, 0, 0, 0.5);
            font-weight: 700;
            margin: 20px 0;
        }


        
          @media screen and (max-width: 700px) {
            .sidebarright {
              display:none;
            }
            .hiddenitemfull{
              display:none;
            }
            .hiddenitem{
              display:none;
            }

            a.hiddenitem{
              display:none;
            }

            .tm{
            padding-top: 100px;

            }
    
            .sidebar {
              width: 100%;
              height: auto;
              position: relative;
              text-align: center;
              position: fixed;
              bottom: 0;
            }
            .sidebar a {
              float: left;
              width:20%;
              padding:16px;
              
            }
            .topnav{
              width: 100%;
              height: auto;
              position: relative;
              text-align: center;
              position: fixed;
              // bottom: 0;
            }
            .topnav a {
              float: left;
              // width:50%;
              padding:8px;
              
            }
            // div.content {
            //   // margin-left: 0;
            //   // margin-left: 10%;
            //   // margin-right: 10%;
            //   // padding: 1px 16px;
            //   // height: 100vh;
            //   // padding-top: 90px;
            //   width : 100px;
            //   // margin: auto;

            // }

            div.content {
              margin-left: 0px;
              width : 100%;
              min-width: 300px;
            }
            .hiddentext{
              font-size: 0px;
            }
          }
          @media screen and (max-width: 1000px) and (min-width: 700px) {
            .hiddenitem{
              display:none;
            }
            .sidebarright {
              display:none;
            }
            .topnav {
              display:none;
            }
            .sidebar {
              width: 10%;
              height: 100hv;
              position: relative;
              text-align: center;
              position: fixed;
            }
            div.content {
              margin-left: 18%;
              padding-top: 0px;
              width : 72%;
            }
            .hiddentext{
              font-size: 0px;
            }
            
          }
          // @media screen and (max-width: 400px) {
          //   .sidebar a {
          //     text-align: center;
          //     float: none;
          //   }
          // }
          @media screen and (min-width: 1000px) {
            .topnav {
              display:none;
            }
            .hiddenitemfull{
              display:none;
            }

          }
        `}
      </style>

      <main>
        <div className="sidebar ">
          {/* <a className="active" href="#home">
            Home
          </a> */}
          <Link href={"/"}>
            <div className="hiddenitem">
              <a href="/">
                <Image
                  src={logofull}
                  alt="Picture of the author"
                  width="100%"
                  height="38px"
                  placeholder="blur"
                />
              </a>
            </div>
          </Link>

          <Link href={"/index2"}>
            <div className="hiddenitemfull">
              <a>
                <Image
                  src={logo1}
                  alt="Picture of the author"
                  width="35px"
                  height="35px"
                  placeholder="blur"
                />
              </a>
            </div>
          </Link>

          <Link href={"/"}>
            <a className={router.pathname == "/" ? "active" : ""}>
              <i className="bi bi-house"></i>
              <span className="hiddentext"> Home</span>
            </a>
          </Link>
          <Link href={"/Search"}>
            <a className={router.pathname == "/Search" ? "active" : ""}>
              <i className="bi bi-search" />
              <span className="hiddentext"> Search</span>
            </a>
          </Link>
          <Link href={"/Contact"}>
            <a className={router.pathname == "/Contact" ? "active" : ""}>
              <i className="bi bi-plus-square" />
              <span className="hiddentext"> Contact</span>
            </a>
          </Link>
          <Link href={"/Notification"}>
            <a
              className={
                router.pathname == "/Notification"
                  ? "active hiddenitem"
                  : "hiddenitem"
              }
            >
              <i className="bi bi-heart" />
              <span className="hiddentext"> Notification</span>
            </a>
          </Link>

          <Link href={"/Direct"}>
            <a className={router.pathname == "/Direct" ? "active" : ""}>
              <i className="bi bi-chat" />
              <span className="hiddentext"> Direct</span>
            </a>
          </Link>
          <Link href={"/Profile"}>
            <a className={router.pathname == "/Profile" ? "active" : ""}>
              <i className="bi bi-person" />
              <span className="hiddentext"> Profile</span>
            </a>
          </Link>
        </div>
        <>{children}</>
      </main>
    </div>
  );
}
