import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Swal from "sweetalert2";

export default function Home() {
  const bntyel = {
    background: "#fcd46e",
    border: "2px solid #4e2711",
  };
  const bntyel2 = {
    background: "#fff5de",
    border: "2px solid #4e2711",
    color: "#4e2711",
  };
  const bntyel3 = {
    background: "#fcd46e",
    border: "2px solid #4e2711",
    color: "#4e2711",
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <style>
        {`

.loginbnt {
  background: #fcd46e;
  border: 2px solid #4e2711;
  color: #4e2711;
  width: 150px;
  height: 50px;
  border-radius: 4px;
}

.box {
  width: 300px;
  height: 220px;
  background-color: #f38271;
  border: solid 2px #515050;
}

.box2 {
  width: 350px;
  height: 80px;
  background-color: #adb7dc;
  border: solid 2px #515050;
  margin-bottom: 50px;
}
.opacity-animate {
  animation: opt-animation 0.5s;
  -webkit-animation-fill-mode: forwards;
  animation-fill-mode: forwards;
}

.modal {
  color: #4e2711;
  margin: 0;
  padding: 0;

  width: 100%;
  height: 100vh;

  background: #df9af7;
  background-image: linear-gradient(
      rgba(244, 185, 215) 0.3em,
      transparent 0.3em
    ),
    linear-gradient(90deg, rgba(244, 185, 215) 0.3em, transparent 0.3em);
  background-size: 6em 6em;
}

@-webkit-keyframes opt-animation {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@-moz-keyframes opt-animation {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@-o-keyframes opt-animation {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes opt-animation {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
        `}
      </style>
      <main className={styles.main}>
        {/* <div className="row justify-content-center">
          <div className="col-12 box">
            
            <img
              src="https://user-images.githubusercontent.com/12670730/113008567-6ebdcb80-9177-11eb-91bd-6863196d9cd3.png"
              alt="jacket"
              width="200px"
            />
          </div>
          <div className="col-12 box2"></div>
        </div> */}

        {/* <div className="row justify-content-center">
          <div className="col-7 box">
            RegisterRegisterRegisterRegisterRegisterRegisterRegisterRegisterRegister
          </div>
        </div> */}

        <div className="row">
          <div className="col-12 ">
            <div className="row justify-content-evenly">
              <div className="col-6 ">
                <button
                  type="button"
                  className="loginbnt"
                  data-bs-toggle="modal"
                  data-bs-target="#staticBackdrop"
                >
                  Login
                </button>
              </div>
              <div className="col-6">
                <button
                  type="button"
                  className="loginbnt"
                  data-bs-toggle="modal"
                  data-bs-target="#staticBackdrop1"
                >
                  Register
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* <div className="container text-center">
          <div className="row justify-content-md-center">
            <div className="col-10">
              <div className="row justify-content-md-center ">
                <div className="col col-lg-2 loginbnt">1 of 3</div>
                <div className="col-md-auto loginbnt">Variable width content</div>
                <div className="col col-lg-2 loginbnt">3 of 3</div>
              </div>
            </div>
          </div>
        </div> */}

        <div
          className="modal"
          id="staticBackdrop"
          tabindex="-1"
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog modal-dialog-centered">
            <div className="modal-content">
              <div className="card text-center border-0">
                <div className="card-header" style={bntyel}>
                  Login
                  {/* <i className="bi bi-x-lg"></i> */}
                  <button
                    type="button"
                    className="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                    style={{ position: "relative", right: "-43%" }}
                  ></button>
                </div>

                <div className="card-footer" style={bntyel2}>
                  <form>
                    <div className="d-grid gap-2 col-9 mx-auto mt-3">
                      <input
                        type="text"
                        className="form-control"
                        id="exampleInputEmail1"
                        aria-describedby="emailHelp"
                        placeholder="Username"
                        style={bntyel3}
                      />
                    </div>
                    <div className="d-grid gap-5 col-9 mx-auto mt-3">
                      <input
                        type="password"
                        className="form-control"
                        id="exampleInputPassword1"
                        placeholder="Password"
                        style={bntyel3}
                      />
                    </div>

                    <button type="submit" className="btn mt-3" style={bntyel}>
                      Enter
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div
          className="modal"
          id="staticBackdrop1"
          tabindex="-1"
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog modal-dialog-centered">
            <div className="modal-content">
              <div className="card text-center border-0">
                <div className="card-header" style={bntyel}>
                  Register
                  {/* <i className="bi bi-x-lg"></i> */}
                  <button
                    type="button"
                    className="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                    style={{ position: "relative", right: "-41%" }}
                  ></button>
                </div>

                <div className="card-footer" style={bntyel2}>
                  <form>
                    <div className="d-grid gap-2 col-9 mx-auto mt-3">
                      <input
                        type="text"
                        className="form-control"
                        id="exampleInputEmail1"
                        aria-describedby="emailHelp"
                        placeholder="Username"
                        style={bntyel3}
                      />
                    </div>
                    <div className="d-grid gap-2 col-9 mx-auto mt-3">
                      <input
                        type="mail"
                        className="form-control"
                        id="exampleInputEmail1"
                        aria-describedby="emailHelp"
                        placeholder="Email"
                        style={bntyel3}
                      />
                    </div>
                    <div className="d-grid gap-5 col-9 mx-auto mt-3">
                      <input
                        type="password"
                        className="form-control"
                        id="exampleInputPassword1"
                        placeholder="Password"
                        style={bntyel3}
                      />
                    </div>
                    <div className="d-grid gap-5 col-9 mx-auto mt-3">
                      <input
                        type="password"
                        className="form-control"
                        id="exampleInputPassword1"
                        placeholder="Confrim Password"
                        style={bntyel3}
                      />
                    </div>

                    <button type="submit" className="btn mt-3" style={bntyel}>
                      Enter
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* <div className="container d-grid gap-2 col-4 mx-auto">
          <div className="row">
            <div className="col-12">
              <div className="card text-center border-0">
                <div className="card-header" style={bntyel}>
                  Login
                  <i className="bi bi-x-lg"></i>
                </div>

                <div className="card-footer" style={bntyel2}>
                  <form>
                    <div className="d-grid gap-2 col-9 mx-auto mt-3">
                      <input
                        type="text"
                        className="form-control"
                        id="exampleInputEmail1"
                        aria-describedby="emailHelp"
                        placeholder="Username"
                        style={bntyel3}
                      />
                    </div>
                    <div className="d-grid gap-5 col-9 mx-auto mt-3">
                      <input
                        type="password"
                        className="form-control"
                        id="exampleInputPassword1"
                        placeholder="Password"
                        style={bntyel3}
                      />
                    </div>

                    <button type="submit" className="btn mt-3" style={bntyel}>
                      Enter
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div> */}
      </main>
    </div>
  );
}
